### PR TITLE
Fix incorrect typing_extensions pin

### PR DESCRIPTION
**Pull request by maresb**
Source: https://github.com/willmcgugan/rich/blob/v10.15.2/pyproject.toml

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Any reason this feedstock isn't noarch? It seems like it'd be a good candidate.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by jan-janssen** [comment]
> Any reason this feedstock isn't noarch? It seems like it'd be a good candidate.

To my knowledge the selectors `dataclasses >=0.7,<0.9  # [py>=36 and py<37]` are not compatible with `noarch` packages. Still as Python 3.6 is no longer supported we can basically remove this line which should allow us to switch to `noarch`.

**Comment by maresb** [comment]
For `py>=37` the `dataclasses` package [is empty](https://conda-forge.org/docs/maintainer/knowledge_base.html#empty-python-packages), so I think it should be fine to switch to `noarch` in any case.

**Comment by jan-janssen** [comment]
> For `py>=37` the `dataclasses` package [is empty](https://conda-forge.org/docs/maintainer/knowledge_base.html#empty-python-packages), so I think it should be fine to switch to `noarch` in any case.

It might be that `pip check` complains, but I have to admit I have not checked for some time. I created this package recipe in summer 2020 and so far it worked automatically with the automated pull requests and automated merge after successful CI. So definitely feel free to migrate it to `noarch`.

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@jan-janssen, done! :smile:

**Comment by jan-janssen** [comment]
Perfect thanks a lot - by the way feel free to add yourself as maintainer if you want to.

**Pull request merged**
