### PR TITLE
Try Python 3.6

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Review by willmcgugan — APPROVED** [review]

**Comment by jan-janssen** [comment]
The python 3.6 builds for windows fail but those for Linux and Mac Os work fine.

**Comment by jan-janssen** [comment]
> That’s strange. Any error messages? I have Windows tests working on GH Actions.

It is an issue with the conda dependencies not with your code.

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
