### PR TITLE
clean up deps, add jupyter output, run tests with coverage

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Notes:
- removes `commonmark` :tada: 
- update bottom python pin
- updates some metadata (URLs, description, etc)
- uses poetry-generated `setup.py` as source of truth
- adds `rich-with-jupyter` with appropriate pin (would love to see that support `ipywidgets 8`!
- adds `_rich-with-tests` with coverage (avoids putting the tests in the core or `jupyter` package)
- happy to add myself as a maintainer, if there are concerns about any new complexity

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/rich ready for review! If desired, I can roll this back to _just_ the `commonmark` removal (and the metadata updates), and/or add myself as a maintainer.

thanks for maintaining this!

**Review by jan-janssen — APPROVED** [review]
Looks good to me and feel free to add yourself as maintainer

**Comment by bollwyvl** [comment]
> Looks good to me and feel free to add yourself as maintainer

thanks for the speedy review. have added self!

**Pull request merged**
